version: '2.1'
volumes:
  travela_data:
    external: true
  redis_data:
    external: true

services:
  gitbase:
    image: srcd/gitbase:latest
    expose:
      - '3306'
    ports:
      - '3306:3306'
    volumes:
      - /local/apps/andela/travel-tool:/opt/repos
  database:
    image: postgres:9.6-alpine
    expose:
      - '5432'
    ports:
      - '5433:5432'
    volumes:
      - travela_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: travela
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 10s
      retries: 5
  redis:
    image: redis:5.0-alpine
    expose:
      - '6379'
    ports:
      - '6380:6379'
    volumes:
      - redis_data:/data
